name: Build and Deploy Sphinx

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: actions/checkout@v3
      uses: actions/checkout@v3

    - name: photon-platform/action-deploy-sphinx-gh-pages
      uses: photon-platform/action-deploy-sphinx-gh-pages@v18
      with:
        modules_repo_urls: 'https://github.com/photon-platform/publish.git'
        python_version: '3.12'  
